.TH ecxcli "1" "Jan 2026" "version 1.1.1" "ecxcli Manual"
.SH NAME
ecxcli - manual page for ecxcli version 1.1.1
.SH SYNOPSIS
.B ecxcli
[--help] [--markdown] [--version]
.SH DESCRIPTION
Command line for ecx.
.SH OPTIONS



Optional switches:
   --help, -h
    Print this help message
   --markdown, -md
    Save this help message in a Markdown file
   --version, -v
    Print version
