bv – ecx
bv Function
19 statements
Source File
public pure elemental function bv(U, OCV, j0, jdla, jdlc, aa, ac, za, zc, A, T) result(I)
Compute Butler Volmer equation with mass transport.
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: U
Electrochemical potential in V.
real(kind=dp), intent(in) :: OCV
Open Circuit Voltage in V.
real(kind=dp), intent(in) :: j0
Exchange current density in A.cm-2.
real(kind=dp), intent(in) :: jdla
Anodic diffusion limiting current density in A.cm-2.
real(kind=dp), intent(in) :: jdlc
Cathodic diffusion limiting current density in A.cm-2.
real(kind=dp), intent(in) :: aa
Anodic transfer coefficient.
real(kind=dp), intent(in) :: ac
Cathodic transfer coefficient.
real(kind=dp), intent(in) :: za
Number of exchnaged electrons in the anodic branch.
real(kind=dp), intent(in) :: zc
Number of exchnaged electrons in the cathodic branch.
real(kind=dp), intent(in) :: A
Area in cm2.
real(kind=dp), intent(in) :: T
Temperature in °C.
Return Value real(kind=dp)
Calls
Call graph
bv calls kte, sbv
sbv calls kte