ecx_kinetics_bv – ecx
ecx_kinetics_bv Function
19 statements
Source File
public pure elemental function ecx_kinetics_bv(U, OCV, j0, jdla, jdlc, aa, ac, za, zc, A, T) result(I)
Compute Butler Volmer equation with mass transport.
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in) :: U
Electrochemical potential in V.
real(kind=real64), intent(in) :: OCV
Open Circuit Voltage in V.
real(kind=real64), intent(in) :: j0
Exchange current density in A.cm-2.
real(kind=real64), intent(in) :: jdla
Anodic diffusion limiting current density in A.cm-2.
real(kind=real64), intent(in) :: jdlc
Cathodic diffusion limiting current density in A.cm-2.
real(kind=real64), intent(in) :: aa
Anodic transfer coefficient.
real(kind=real64), intent(in) :: ac
Cathodic transfer coefficient.
real(kind=real64), intent(in) :: za
Number of exchnaged electrons in the anodic branch.
real(kind=real64), intent(in) :: zc
Number of exchnaged electrons in the cathodic branch.
real(kind=real64), intent(in) :: A
Area in cm2.
real(kind=real64), intent(in) :: T
Temperature in °C.
Return Value real(kind=real64)
Calls
Call graph
ecx_kinetics_bv calls ecx_kinetics_sbv, kte
ecx_kinetics_sbv calls kte