#!/usr/bin/env bash

DOC_MAIN=main
DOC_SRC_DIR=src
DOC_BUILD_DIR=build
DOC_DEP_DIR=build/dependencies
DOC_FORMATS="man txt latex pdf html"
DOC_TEX=pdflatex
DOC_BIB=biber
DOC_NCL=makeindex
DOC_MK4CFG=make4ht.cfg
DOC_MK4BUILD=make4ht.mk4
PREP_DOC_DIR=../prep/doc

GIT="bibfiles drawings"

FLAGS_RM=-rfv
FLAGS_MV=-fv

make_dirs (){
    echo "[INFO]: Generating folders."
    for format in $DOC_FORMATS; do
        mkdir -p $DOC_BUILD_DIR/$format
        mkdir -p $DOC_DEP_DIR
    done
    echo "[INFO]: Folders created."
}


dowload_dependencies () {
    echo "[INFO]: Downloading dependencies."
    for i in $GIT;do
        url="https://github.com/MilanSkocic/$i.git"
        if [[ ! -d $DOC_DEP_DIR/$i/ ]]; then 
            git clone $url $DOC_DEP_DIR/$i; 
            if [[ $?>0 ]]; then 
                echo "The repo $i could not be retrieved."; 
            fi
        fi
    done
    url=$DOC_DEP_DIR/drawings/figures/png
    target=PEC-*.png
    cp -fv $url/$target ./src/figures/

    url=$DOC_DEP_DIR/drawings/figures/png
    target=EIS-*.png
    cp -fv $url/$target ./src/figures/

    url=$DOC_DEP_DIR/bibfiles
    target=references.bib
    cp -fv $url/$target ./src/references.bib
    echo "[INFO]: Dependencies downloaded."
}

make_man () {
    echo "[INFO]: Generating man pages."
    files=$(ls $PREP_DOC_DIR/*.prepdoc)
    for file in $files; do
        man_name=$(basename -s .prepdoc $file)
        man_section=$(echo $man_name | cut -d "." -f 2)
        man_name_nosec=$(echo $man_name | cut -d "." -f 1)
        man_number=${man_section:0:1}
        
        fp_man=$( echo $file | sed "s/.prepdoc//g")
        fp_man=$( echo $fp_man | sed "s:$PREP_DOC_DIR:$DOC_BUILD_DIR/man:g")
        
        fp_mantxt="$fp_man.txt"
        fp_mantxt=$( echo $fp_mantxt | sed "s:$DOC_BUILD_DIR/man:$DOC_BUILD_DIR/txt:g")
        
        fp_manhtml="$fp_man.html"
        fp_manhtml=$( echo $fp_manhtml | sed "s:$DOC_BUILD_DIR/man:$DOC_BUILD_DIR/html:g")
        
        fp_mantex="$fp_man.tex"
        fp_mantex=$( echo $fp_mantex | sed "s:$DOC_BUILD_DIR/man:$DOC_BUILD_DIR/latex:g")
        
        fp_manpdf="$fp_man.pdf"
        fp_manpdf=$( echo $fp_manpdf | sed "s:$DOC_BUILD_DIR/man:$DOC_BUILD_DIR/pdf:g")
       
        # man
        if [[ $VERBOSE == 1 ]]; then echo "   $file -> $fp_man"; fi
        txt2man -s $man_section -t $man_name_nosec -r $FPM_NAME -v "Library Functions Manual"  $file > $fp_man
        rm $FLAGS_RM "$fp_man.gz"
        gzip -k $fp_man
        
        # txt
        if [[ $VERBOSE == 1 ]]; then echo "   $fp_man -> $fp_mantxt"; fi
        man $fp_man > $fp_mantxt
        
        # html 
        if [[ $VERBOSE == 1 ]]; then echo "   $fp_man -> $fp_manhtml"; fi
        man2html -r $fp_man > $fp_manhtml
        
        # tex
        if [[ $VERBOSE == 1 ]]; then echo "   $fp_man -> $fp_mantex";fi
        echo "" > $fp_mantex
        echo "\\begin{Verbatim}[frame=lines,label=$man_name]" >> $fp_mantex
        man -l $fp_man >> $fp_mantex
        echo "\\end{Verbatim}" >> $fp_mantex
        echo "" >> $fp_mantex
        echo "" >> $fp_mantex
        echo "" >> $fp_mantex
        
        # pdf
        man -Tpdf -l $fp_man > $fp_manpdf
    done
    echo "[INFO]: Man pages created."
}

make_txt () {
    echo "[INFO]: Generating text documentation."
    DOC="$DOC_BUILD_DIR/txt/$FPM_NAME.txt"
    rm $FLAGS_RM $DOC
    files=$(ls $DOC_BUILD_DIR/txt/*.txt)
        echo "$FPM_NAME - $FPM_VERSION                              " > $DOC
        echo "" >> $DOC

        for i in $files; do
        echo "--------------------------------------------------------------------------------" >> $DOC
        cat $i >> $DOC
        echo "--------------------------------------------------------------------------------" >> $DOC
        echo "" >> $DOC
        echo "" >> $DOC
        done
    echo "[INFO]: Text documentation created."
}

make_latex () {
    echo "[INFO]: Generating latex documentation."
    DOC="$DOC_BUILD_DIR/latex/$FPM_NAME.tex"
    rm $FLAGS_RM $DOC
    files=$(ls $DOC_BUILD_DIR/latex/*.tex)
    echo "" > $DOC
    for file in $files; do
        man_name=$(basename -s .tex $file)
        man_section=$(echo $man_name | cut -d "." -f 2)
        man_number=${man_section:0:1}
        echo "\\section{$man_name\\index{$man_name}}\\label{sec_$man_name}" >> $DOC
        echo "\\input{build/latex/$(basename $file)}" >> $DOC
        echo "" >> $DOC
    done
    echo "[INFO]: Latex documentation created."
    echo "[INFO]: Writing LaTeX variable to $fp"
    fp=src/make.in.tex
    echo "% Autogenerated" > $fp
    echo "\\def\\NAME{$FPM_NAME}" >> $fp
    echo "\\def\\VERSION{$FPM_VERSION}" >> $fp
    echo "\\def\\AUTHOR{$FPM_AUTHOR}" >> $fp
    echo "[INFO]: LaTeX variables written."
}

make_dirs
dowload_dependencies
make_man
make_txt
make_latex


$DOC_TEX -output-directory=./$DOC_BUILD_DIR -synctex=1 $DOC_SRC_DIR/$DOC_MAIN.tex
$DOC_BIB ./$DOC_BUILD_DIR/$DOC_MAIN.bcf --output-file ./$DOC_BUILD_DIR/$DOC_MAIN.bbl
# cp $DOC_SRC_DIR/references.bib $DOC_BUILD_DIR/
# cd $DOC_BUILD_DIR
# $DOC_BIB $DOC_MAIN.aux 
#cd ..

# index
$DOC_NCL ./$DOC_BUILD_DIR/$DOC_MAIN.nlo -s nomencl.ist -o ./$DOC_BUILD_DIR/$DOC_MAIN.nls
$DOC_NCL ./$DOC_BUILD_DIR/$DOC_MAIN.idx

# link
$DOC_TEX -output-directory=./$DOC_BUILD_DIR -synctex=1 $DOC_SRC_DIR/$DOC_MAIN.tex
$DOC_TEX -output-directory=./$DOC_BUILD_DIR -synctex=1 $DOC_SRC_DIR/$DOC_MAIN.tex

# copy
cp -rf $DOC_BUILD_DIR/$DOC_MAIN.pdf $DOC_BUILD_DIR/pdf/$FPM_NAME.pdf
cp ./$DOC_BUILD_DIR/$DOC_MAIN.idx ./$DOC_BUILD_DIR/$DOC_MAIN.4idx

# html
make4ht -c $DOC_MK4CFG -d $DOC_BUILD_DIR/html -B $DOC_BUILD_DIR -e $DOC_MK4BUILD $DOC_SRC_DIR/$DOC_MAIN.tex -a info

rm $FLAGS_RM $DOC_MAIN.*
rm $FLAGS_RM $DOC_BUILD_DIR/$DOC_MAIN.*
