include ../make.in

all: pdf info html

none:
	./build.sh

info:
	./build.sh info

pdf:
	./build.sh pdf

html:
	./build.sh html

clean:
	rm -rf build/*
	rm -f *.aux *.cp main.cps *.info *.log *.toc *.out *.synctex* *.idx *.ilg *.ind *.cps
