capi_bv – ecx
capi_bv Subroutine
MIT
16 statements
Source File
public pure subroutine capi_bv(U, OCV, j0, jdla, jdlc, aa, ac, za, zc, A, T, I, n) bind(c, name="ecx_kinetics_bv")
Compute Butler Volmer equation without mass transport.
Arguments
Type Intent Optional Attributes Name
real(kind=c_double), intent(in) :: U(n)
Potential in volts.
real(kind=c_double), intent(in), value :: OCV
Open circuit potential in volts.
real(kind=c_double), intent(in), value :: j0
Exchange current density in A.cm-2
real(kind=c_double), intent(in), value :: jdla
Anodic diffusion limiting current density in A.cm-2.
real(kind=c_double), intent(in), value :: jdlc
Cathodic diffusion limiting current density in A.cm-2.
real(kind=c_double), intent(in), value :: aa
Anodic transfert coefficient.
real(kind=c_double), intent(in), value :: ac
Cathodic transfert coefficient.
real(kind=c_double), intent(in), value :: za
Number of exchanged electrons in anodic branch.
real(kind=c_double), intent(in), value :: zc
Number of exchanged electrons in cathodic branch.
real(kind=c_double), intent(in), value :: A
Area in cm2.
real(kind=c_double), intent(in), value :: T
Temperature in °C.
real(kind=c_double), intent(out) :: I(n)
Current in A.
integer(kind=c_size_t), intent(in), value :: n
Size of U and I.
Calls
Call graph
capi_bv calls bv
bv calls kte, sbv
sbv calls kte