kTe – ecx
kTe Function
MIT
6 statements
Source File
public pure elemental function kTe(T) result(r)
Compute the thermal voltage.
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: T
Temperature in °C.
Return Value real(kind=dp)
Thermal voltage in V.
Called by
Call graph
bv calls kte, sbv
capi_kte calls kte
nernst calls kte
sbv calls kte
capi_bv calls bv
capi_nernst calls nernst
capi_sbv calls sbv