mm – ecx
mm Subroutine
MIT
27 statements
Source File
public subroutine mm(p, w, zout, n)
Compute the measurement model.
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: p(:)
Parameters.
real(kind=dp), intent(in) :: w(:)
Angular frequencies in rad.s-1
complex(kind=dp), intent(out) :: zout(:)
Complex impedance in Ohms.
integer(kind=int32), intent(in) :: n
Number of voigt elements.
Calls
Call graph
mm calls z
z calls zc, zg, zl, zo, zq, zr, zt, zw