z – ecx
z Subroutine
MIT
50 statements
Source File
public subroutine z(p, w, zout, e, errstat, errmsg)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: p(:)
real(kind=dp), intent(in) :: w(:)
Angular frequencies in rad.s-1
complex(kind=dp), intent(out) :: zout(:)
Complex impedance in Ohms.
character(len=1), intent(in) :: e
Electrochemical element: R, C, L, Q, O, T, G
integer(kind=int32), intent(out) :: errstat
Error status
character(len=:), intent(out), pointer :: errmsg
Error message
Calls
Called by
Call graph
z calls zc, zg, zl, zo, zq, zr, zt, zw
capi_z calls z
mm calls z