zg – ecx
zg Function
MIT
10 statements
Source File
public pure elemental function zg(w, G, K) result(Z)
Compute the complex impedance of the Gerisher element.
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: w
Angular frequency in rad.s^-1.
real(kind=dp), intent(in) :: G
Pseudo-Resistance in Ohms.s^(1/2).
real(kind=dp), intent(in) :: K
Offset in rad.s^-1.
Return Value complex(kind=dp)
Complex impedance in Ohms.
Called by
Call graph
z calls zg
capi_z calls z
mm calls z