/**
* @file
* @brief Version - autogenerated.
*/

#ifndef ecx_VERSION_H
#define ecx_VERSION_H
#if _MSC_VER
#define ADD_IMPORT __declspec(dllimport)
#else
#define ADD_IMPORT
#endif
ADD_IMPORT extern const char ecx_version_capi_version[ 6];
#endif

