.TH ecx 3 "26 August 2026" "0.1.0" "Library calls"
.SH NAME
\fBecx \fP- library for electrochemistry
\fB
.SH LIBRARY
ecx (\fB-libecx\fP, \fB-lecx\fP)
.SH SYNOPSIS
.nf
.fam C
  ecx (Fortran): use ecx
  ecx (C): include "ecx.h"
  ecx (python): import pyecx

.fam T
.fi
.fam T
.fi
.SH DESCRIPTION
ecx a Fortran library for providing a collection of routines for electrochemistry.
A C API allows usage from C, or can be used as a basis for other wrappers.
A Python wrapper allows easy usage from Python.
.PP
It covers:
.RS
.TP
.B
o kinetics
Nernst, Butler-Volmer
.TP
.B
o electrochemical
Impedance, Admittance, Circuit Elements, Equivalent Circuits
.TP
.B
o photoelectrochemistry
Photocurrent, Band-gap, space charge.
.RE
.PP
The C API is defined by adding a prefix to the functions from the Fortran
API due to the lack of module/namespace feature in the C language.
The functions are therefore following this template:
(c_prefix)fortran_func.
.SH EXAMPLES
\"{{{
.PP
Example in Fortran:
.nf
.ft CR
    program example_in_f
    use iso_fortran_env
    use ecx
    implicit none
    
    real(real64) :: w(3) = [1.0d0, 1.0d0, 100.0d0]
    real(real64) :: r = 100.0d0
    real(real64) :: p(3) = 0.0d0
    character(len=1) :: e
    integer :: errstat
    complex(real64) :: zout(3)
    character(len=:), pointer :: errmsg
    
    p(1) = r
    e = "R"
    call z(p, w, zout, e, errstat, errmsg)
    print *, zout
    print *, errstat, errmsg
    
    
    end program
.ft R
.fi

.PP
Example in C
.nf
.ft CR
    #include <stdio.h>
    #include <stdlib.h>
    #include "ecx.h"
    
    
    int main(void){
    
        int errstat, i;
        double w[3] = {1.0, 1.0, 1.0};
        double p[3] = {100.00, 0.0, 0.0};
        ecx_cdouble z[3] = {ecx_cbuild(0.0,0.0), 
                            ecx_cbuild(0.0, 0.0), 
                            ecx_cbuild(0.0, 0.0)};
        char *errmsg;
    
        ecx_eis_z(p, w, z, 'R', 3, 3, &errstat, &errmsg);
        
        for(i=0; i<3;i++){
            printf("%f %f \n", creal(z[i]), cimag(z[i]));
        }
        printf("%d %s\n", errstat, errmsg); 
        return EXIT_SUCCESS;
    }
.ft R
.fi

.PP
Example in Python
.nf
.ft CR
    import sys
    sys.path.insert(0, "../py/src/")
    import numpy as np
    import pyecx
    import matplotlib.pyplot as plt
    
    R = 100
    C = 1e-6
    w = np.logspace(6, -3, 100)
    
    p = np.asarray([R, 0.0, 0.0])
    zr = np.asarray(pyecx.z("R", w, p))
    p = np.asarray([C, 0.0, 0.0])
    zc = np.asarray(pyecx.z("C", w, p))
    zrc = zr*zc / (zr+zc)
    print("finish")
    
    fig = plt.figure()
    ax = fig.add_subplot(111)
    
    ax.set_aspect("equal")
    ax.plot(zrc.real, zrc.imag, "g.", label="R/C")
    
    ax.invert_yaxis()
    
    plt.show()
.ft R
.fi
\"}}}

.SH SEE ALSO
.BR ecx (1)
.BR ecx_lib (3)
