.TH ecx 3 "@DATE@" "@VERSION@" "Library calls"
.SH NAME
\fBecx \fP- library for electrochemistry
\fB
.SH LIBRARY
ecx (\fB-libecx\fP, \fB-lecx\fP)
.SH SYNOPSIS
.nf
.fam C
  ecx (Fortran): use ecx
  ecx (C): include "ecx.h"
  ecx (python): import pyecx

.fam T
.fi
.fam T
.fi
.SH DESCRIPTION
ecx a Fortran library for providing a collection of routines for electrochemistry.
A C API allows usage from C, or can be used as a basis for other wrappers.
A Python wrapper allows easy usage from Python.
.PP
It covers:
.RS
.TP
.B
o kinetics
Nernst, Butler-Volmer
.TP
.B
o electrochemical
Impedance, Admittance, Circuit Elements, Equivalent Circuits
.TP
.B
o photoelectrochemistry
Photocurrent, Band-gap, space charge.
.RE
.PP
The C API is defined by adding a prefix to the functions from the Fortran
API due to the lack of module/namespace feature in the C language.
The functions are therefore following this template:
(c_prefix)fortran_func.
