name: CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  release:
    types: [published]

jobs:
  linux:
    runs-on: ubuntu-22.04
    steps:
    - name: Gfortran  
      run: |
        sudo update-alternatives \
          --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 \
          --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-10 \
          --slave /usr/bin/gcov gcov /usr/bin/gcov-10
    - name: Set FPM
      uses: fortran-lang/setup-fpm@v5
      with: 
        fpm-version: "v0.10.0"
    - name: Gfortran version
      run : gfortran --version
    - name: Checkout
      uses: actions/checkout@v4
    - name: Configure
      run: |
        . ./configure.sh
        echo "NAME=$NAME" >> $GITHUB_ENV
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "PLATFORM=$PLATFORM" >> $GITHUB_ENV
        echo "ARCH=$ARCH" >> $GITHUB_ENV
    - name: Compile
      run: |
        chmod u+x build.sh
        ./build.sh
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.NAME }}-${{ env.PLATFORM }}-${{ env.ARCH }}-${{ env.VERSION }}
        path: ./build/install/


  macos: 
    runs-on: macos-13
    steps:
    - name: Gfortran
      run: |
        brew reinstall gcc@10 gfortran
    - name: Set FPM
      uses: fortran-lang/setup-fpm@v5
      with: 
        fpm-version: "v0.10.0"
    - name: Gfortran version
      run : gfortran --version
    - name: Checkout
      uses: actions/checkout@v4
    - name: Configure
      run: |
        . ./configure.sh
        echo "NAME=$NAME" >> $GITHUB_ENV
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "PLATFORM=$PLATFORM" >> $GITHUB_ENV
        echo "ARCH=$ARCH" >> $GITHUB_ENV
    - name: Compile
      run: |
        chmod u+x build.sh
        ./build.sh
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.NAME }}-${{ env.PLATFORM }}-${{ env.ARCH }}-${{ env.VERSION }}
        path: ./build/install/


  windows: 
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps: 
    - name: MSYS2, Gfortran, fpm
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        install: >-
          mingw-w64-x86_64-gcc-fortran
          mingw-w64-x86_64-fpm
          git
          make
          zip
    - name: Gfortran version
      run : gfortran --version
    - name: Checkout
      uses: actions/checkout@v4
    - name: Configure
      run: |
        . ./configure.sh
        echo "NAME=$NAME" >> $GITHUB_ENV
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "PLATFORM=$PLATFORM" >> $GITHUB_ENV
        echo "ARCH=$ARCH" >> $GITHUB_ENV
    - name: Compile
      run: |
        chmod u+x build.sh
        ./build.sh
    - uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Python wheel
      run: |
        py -m pip install -U --user setuptools build wheel
        make -C py python3.9
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.NAME }}-${{ env.PLATFORM }}-${{ env.ARCH }}-${{ env.VERSION }}
        path: ./build/install/

  release:
    runs-on: ubuntu-latest
    needs: 
      - linux
      - macos
      - windows
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    - name: Zip artifacts
      run: |
        cd artifacts
        FOLDERS=$(ls -d */)
        for f in $FOLDERS;do cd $f; zip -r $(basename $f).zip .; cd ..; mv $f/*.zip .; done
        ls -al *.zip
        cd ..
    - name: Release
      if: ${{ github.event_name == 'release' }}
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: artifacts/*.zip
        file_glob: true
        tag: ${{ github.ref }}
        overwrite: true