name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build: [fpm]
        os: [ubuntu-latest]
        gcc: [10] # Version of GFortran we want to use.
        build-type: [debug]
    env:
      FC: gfortran
      CC: gcc
      FPM_FC: gfortran
      FPM_CC: gcc

    steps:
    - name : Checkout
      uses: actions/checkout@v4
    # - uses: fortran-lang/setup-fpm@v2
    #   with: 
    #     fpm-version: 0.9.0
    #     github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install GFortran (Linux)
      if: ${{ contains(matrix.os, 'ubuntu') }}
      run: |
        sudo update-alternatives \
          --install /usr/bin/gcc gcc /usr/bin/gcc-${{ matrix.gcc }} 100 \
          --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-${{ matrix.gcc }} \
          --slave /usr/bin/gcov gcov /usr/bin/gcov-${{ matrix.gcc }}
    - name: Configure
      run: . ./configure.sh
    - name: Gfortran version
      run : gfortran --version
    
