name: CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  release:
    types: [published]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-13, windows-latest]
        toolchain:
          - {compiler: gcc, version: 10}
        include:
          - os: ubuntu-22.04
            os-arch: linux-x86_64
          - os: macos-13
            os-arch: macos-x86_64
          - os: windows-latest
            os-arch: windows-x86_64
            exe: .exe
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Fortran compiler
        uses: fortran-lang/setup-fortran@v1.6.1
        id: setup-fortran
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}
      
      - name: gfortran version
        run: |
          which gfortran-${{ matrix.toolchain.version }}
          which gfortran
          gfortran --version

      - name: Install fpm
        uses: fortran-lang/setup-fpm@v5
        with:
          fpm-version: "v0.10.0"

      - name: Compile
        run: |
          . configure.sh
          make


