name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set Gfortran  
      run: |
        sudo update-alternatives \
          --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 \
          --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-10 \
          --slave /usr/bin/gcov gcov /usr/bin/gcov-10
    - name: Set FPM
      uses: fortran-lang/setup-fpm@v5
      with: 
        fpm-version: "v0.9.0"
    - name: Checkout
      uses: actions/checkout@v4
    - name: Gfortran version
      run : gfortran --version
    - name: Compile
      run: |
        fpm clean --all
        fpm build --profile=debug 

  macos: 
    runs-on: macos-latest
    steps:
    - name: Set Gfortran and fpm
      run: ls
  
  windows_MSYS2: 
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps: 
    - name: MSYS2, Gfortran, fpm
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        install: >-
          mingw-w64-x86_64-gcc-fortran
          mingw-w64-x86_64-fpm
          git
          curl
          make
    - name: Gfortran version
      run : gfortran --version
    - name: Checkout
      uses: actions/checkout@v4
    - name: Compile
      run: |
        . ./configure.sh
        make