name: CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  linux:
    runs-on: ubuntu-22.04
    steps:
    - name: Gfortran  
      run: |
        sudo update-alternatives \
          --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 \
          --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-10 \
          --slave /usr/bin/gcov gcov /usr/bin/gcov-10
    - name: Set FPM
      uses: fortran-lang/setup-fpm@v5
      with: 
        fpm-version: "v0.10.0"
    - name: Gfortran version
      run : gfortran --version
    - name: Checkout
      uses: actions/checkout@v4
    - name: Compile
      run: |
        . ./configure.sh
        chmod u+x build.sh
        ./build.sh
        echo "NAME=$NAME" >> $GITHUB_ENV
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "PLATFORM=$PLATFORM" >> $GITHUB_ENV
        echo "ARCH=$ARCH" >> $GITHUB_ENV

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.NAME }}-${{ env.VERSION }}-${{ env.PLATFORM }}-${{ env.ARCH }}
        path: ./build/install/


  macos: 
    runs-on: macos-13
    steps:
    - name: Gfortran
      run: |
        brew reinstall gcc@10 gfortran
    - name: Set FPM
      uses: fortran-lang/setup-fpm@v5
      with: 
        fpm-version: "v0.10.0"
    - name: Gfortran version
      run : gfortran --version
    - name: Checkout
      uses: actions/checkout@v4
    - name: Compile
      run: |
        . ./configure.sh
        chmod u+x build.sh
        ./build.sh
        echo "NAME=$NAME" >> $GITHUB_ENV
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "PLATFORM=$PLATFORM" >> $GITHUB_ENV
        echo "ARCH=$ARCH" >> $GITHUB_ENV

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.NAME }}-${{ env.VERSION }}-${{ env.PLATFORM }}-${{ env.ARCH }}
        path: ./build/install/


  windows: 
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps: 
    - name: MSYS2, Gfortran, fpm
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        install: >-
          mingw-w64-x86_64-gcc-fortran
          mingw-w64-x86_64-fpm
          git
          make
          zip
    - name: Gfortran version
      run : gfortran --version
    - name: Checkout
      uses: actions/checkout@v4
    - name: Compile
      run: |
        . ./configure.sh
        ./build.sh
        echo "NAME=$NAME" >> $GITHUB_ENV
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "PLATFORM=$PLATFORM" >> $GITHUB_ENV
        echo "ARCH=$ARCH" >> $GITHUB_ENV

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.NAME }}-${{ env.VERSION }}-${{ env.PLATFORM }}-${{ env.ARCH }}-gcc-msys2
        path: ./build/install/

  release:
    needs: 
      - unix
      - macos
      - windows
    if: ${{ github.event_name == 'push' }}
    run: |
      git tag --force 'current'
      git push --tags --force