name: CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  release:
    types: [published]

jobs:

  build_unix:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-13]
        toolchain:
          - {compiler: gcc, version: 10}
        include:
          - os: ubuntu-22.04
            os-arch: linux-x86_64
          - os: macos-13
            os-arch: macos-x86_64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Fortran compiler
        uses: fortran-lang/setup-fortran@v1.6.1
        id: setup-fortran
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}
      
      - name: Install fpm
        uses: fortran-lang/setup-fpm@v5
        with:
          fpm-version: "v0.10.0"
    
      - name: Gfortran version
        run : gfortran --version

      - name: Compile
        run: |
          which gfortran
          gfortran --version
          . configure.sh
          make
      
  build_windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps: 
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: MSYS2, Gfortran, fpm
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: >-
            mingw-w64-x86_64-gcc-fortran
            mingw-w64-x86_64-fpm
            git
            make
      
      - name: Gfortran version
        run : gfortran --version
      
      - name: Compile
        run: |
          . ./configure.sh
          make

      - name: Upload artifacts
        uses: actions/upload-artifacts@v4
        with:
          name: windows-msys2
          path: ./build/libecx.*



