name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    # - uses: fortran-lang/setup-fpm@v2
    #   with: 
    #     fpm-version: 0.9.0
    #     github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Configure
      run: . ./configure
