name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        toolchain:
          - {compiler: gcc, version: 10}
          #- {compiler: intel-classic, version: '2021.10'}

    steps:
    - name: Set Compilers  
      uses: fortran-lang/setup-fortran@v1.3
      id: setup-fortran
      with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set FPM
      uses: fortran-lang/setup-fpm@v5
      with: 
        fpm-version: "v0.9.0"
    - name: Gfortran version
      run : gfortran --version
    - name: Compile
      run: |
        fpm clean --all
        fpm build --profile=debug 
  
  windows: 
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps: 
    - name: MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        install: mingw-w64-x86_64-gcc-fortran
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set FPM
      uses: fortran-lang/setup-fpm@v5
      with: 
        fpm-version: "v0.9.0"
    - name: Gfortran version
      run : gfortran --version