name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        gcc: [10] # Version of GFortran we want to use.
    env:
      FC: gfortran
      CC: gcc
      FPM_FC: gfortran
      FPM_CC: gcc
      LIBNAME: ecx
      PYW_DIR: ./pywrapper
      BUILD_DIR: ./build
      INCLUDE_DIR: ./include
      PYW_MOD_DIR: ${PYW_DIR}/py${LIBNAME}
      FPM_FFLAGS: -std=f2008 -pedantic -Wall -Wextra
      FPM_CFLAGS: -std=c11 -pedantic -Wall -Wextra
      FPM_LDFLAGS: -static
      PLATFORM: linux

    steps:
    - name : Checkout
      uses: actions/checkout@v4
    - name: Set FPM
      uses: fortran-lang/setup-fpm@v5
      with: 
        fpm-version: "v0.9.0"
    - name: Install GFortran (Linux)
      if: ${{ contains(matrix.os, 'ubuntu') }}
      run: |
        sudo update-alternatives \
          --install /usr/bin/gcc gcc /usr/bin/gcc-${{ matrix.gcc }} 100 \
          --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-${{ matrix.gcc }} \
          --slave /usr/bin/gcov gcov /usr/bin/gcov-${{ matrix.gcc }}
    - name: Gfortran version
      run : gfortran --version
    - name: Configure
      run: bash . ./configure.sh
    - name: Compile
      run: make 
    
