name: release

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  release:
    types: [published]

jobs:

  release:
    runs-on: ubuntu-latest
    needs: 
      - linux
      - macos
      - windows
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    - name: Zip artifacts
      run: |
        cd artifacts
        FOLDERS=$(ls -d */)
        for f in $FOLDERS;do cd $f; zip -r $(basename $f).zip .; cd ..; mv $f/*.zip .; done
        ls -al *.zip
        cd ..
    - name: Release
      if: ${{ github.event_name == 'release' }}
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: artifacts/*.zip
        file_glob: true
        tag: ${{ github.ref }}
        overwrite: true